controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.35
    wheel_radius: 0.05
    use_stamped_vel: false
    cmd_vel_timeout: 1.0

# joint_state_broadcaster:
#   ros__parameters:

# Tried this but it doesn't work
    # controllers:
    #   - name: "joint_state_broadcaster"
    #     type: "joint_state_broadcaster/JointStateBroadcaster"
    #   - name: "diff_drive_controller"
    #     type: "diff_drive_controller/DiffDriveController"
    #     left_wheel: "left_wheel_joint"
    #     right_wheel: "right_wheel_joint"
    #     publish_rate: 50.0
    #     base_frame_id: "base_link"
    #     wheel_separation: 0.35
    #     wheel_radius: 0.05
    #     use_stamped_velocities: false
    #     cmd_vel_timeout: 0.5 