controller_manager:
  ros__parameters:
    update_rate: 30.0
    use_sim_time: true

    controllers:
      - name: "joint_state_broadcaster"
        type: "joint_state_broadcaster/JointStateBroadcaster"
      - name: "diff_drive_controller"
        type: "diff_drive_controller/DiffDriveController"
        left_wheel: "left_wheel_joint"
        right_wheel: "right_wheel_joint"
        publish_rate: 50.0
        base_frame_id: "base_link"
        wheel_separation: 0.35
        wheel_radius: 0.05
        use_stamped_velocities: false
        cmd_vel_timeout: 0.5